// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgzsvmzuuczompyynxag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnenN2bXp1dWN6b21weXlueGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODQ1MjcsImV4cCI6MjA3MDc2MDUyN30.qF5bnpUdrU0HA3p53wTgzy8J59_OBnBOKVFsYuaM2V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});